server:
  servlet:
    context-path: /rest
  port : 8072
  
spring:
  datasource:
    url: jdbc:mysql://localhost:8889/dbtwitter
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-init-sql: "SET NAMES 'utf8mb4'" 
    
    